---
title: "DEBER_R_HTML"
author: "Gabrielle Galarraga"
date: "26/2/2022"
output:
  html_document:
    mathjax: local
    self_contained: false
    fig_height: 6
    fig_width: 8
    theme: journal
    highlight: zenburn
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: no
      smooth_scroll: yes
---
## Contenidos 
# 1. Ejemplo 1 Operaciones fundamentales.
```{r}
((4+5)*10)/3

```


```{r}
a= 10
b=20 
z=8
q=11
d= ((((q+b)/a)+z)*a)*log(exp(2))
print(d)

```
# 2. Ejemplo 2 Operaciones de realcion.

```{r}
#Menor 
4 < 3 
#Mayor 
10 > 8
#Igual o menor 
4<=((8/2)*3)
# Igual a 
2 == (8/2)
# No igual a 
a !=b
# Comparar palabras
"Mariposa" <"Biflora"
"Pasiflora" >"Mariposa1"
```
# 3. Ejercicio 3 Operaciones Lógicas.

```{r}
# Operador AND
(3+4) & (8/2)
(5>6) & (8/2==2)
#Or y Not
(5<4) | (8/2!=3)
```
# 4. Ejercicio 4 Operación de asignación.

```{r}
# Asignación con "<-"
nombre <-"Gabrielle"
edad <- 20
cabello <- "negro"


# Asignación con "="
especie = "Heliconius erato"
sub_especies = "cyrbia"
sub_especies <- "Melpomene"
Alimentacion <- "Polen"

# Asignación con "<<-"
Ciudad <<-"Tena"
altura <<- 598 # medido en metros
latitud <<- -0.989 
longitud <<- -77.815 # Oeste

```

# 5. Ejercicio 5 Vectores

```{r}
Numeros <- c(0, 1, 2, 3, 4, 5, 6, 7, 8, 9,10,11,12,13,14,15,16,17,18,19,20)
Especies_Heliconius <- c("CYR", "LAT", "HIM", "MEL")
ciudades <- t(c("ciudad1", "ciudad2", "ciudad3")) 
```

```{r}
# verificar el tipo de dato
class(Numeros)
# número de elementos del vector 
length(Numeros)
# escoger un solo elemento del vector
Numeros[6]
# escoger todos excepto el primer elemento del vector
Numeros[-1]
# escoger algunos elementos del vector
Numeros[3:6]
# Operar con escalares 
Numeros*3 + 2
```
# 6. Ejercicio 6 Matrices 

```{r}
# Crear una matriz uniendo vectores como columna
Nombres <- c("Mariana", "Andres", "Stefania", "Marta")
poblacion <- c(2.87, 2.98, 0.55, 0.32) # millones de personas
altura <- c(1.60,1.80,1.65,1.55) # sobre el nivel del mar
datos_Nombres <- cbind(Nombres, poblacion, altura)
datos_Nombres
```
```{r}
# Crear una matriz uniendo vectores como filas
especie1 <- c("LAT", 20, "Napo")
especie2 <- c("CYR", 10, "Cuenca")
especie3 <- c("HIM", 50, "Loja")
especie4 <- c("MEL", 2, "Quito")
especie5 <- c("HEL", 1, "Otavalo")
diversidad <- rbind(especie1, especie2, especie3, especie4, especie5)
diversidad
```
```{r}
# número de elementos de la matriz 
dim(datos_Nombres)
# escoger un solo elemento de la matriz
diversidad[2,1] # elemento de la fila 2 y columna 1

colnames(diversidad) <- c("Especies", "Catidad","Ciudades" )
diversidad
```
# 7. Ejercicio 7 Data Frames
```{r}
Edades = data.frame(estudiante = paste0("Alumno",1:10), calificacion = sample(0:10, 10, replace = TRUE))
Edades
```
